Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -10,6 +10,7 @@ env:
 
 jobs:
   build-and-publish:
+    environment: prod 
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v4
@@ -39,6 +40,16 @@ jobs:
           echo "VSCE_PAT is set and not empty"
         else
           echo "VSCE_PAT is empty or not set"
+        fi
+      env:
+        VSCE_PAT: ${{ secrets.VSCE_PAT }}
+    - name: Publish to Visual Studio Marketplace
+      run: |
+        if [ -z "$VSCE_PAT" ]; then
+          echo "Error: VSCE_PAT is empty"
+          exit 1
+        else
+          vsce publish
         fi
       env:
         VSCE_PAT: ${{ secrets.VSCE_PAT }}
